services:
  lstk-serverless:
    image: localstack/localstack:4.4.0
    container_name: lstk-serverless
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,lambda
      - AWS_DEFAULT_REGION=us-east-1      
    volumes:
      - "${PWD}/setup.sh:/etc/localstack/init/ready.d/setup.sh"
      - "${PWD}/src:/tmp/src"
      - /var/run/docker.sock:/var/run/docker.sock
